version: "2"
services:
  db:
    image: mysql:5.7
    command: --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: car
    ports:
      - "3306:3306"

  myadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: toor
    links:
      - db:db
    ports:
      - "8080:80"
